name: fileheron_server
description: A simple file server written in Dart to deploy a local file server on Windows, MacOS and Linux in seconds.
version: 1.0.5
homepage: https://www.fileheron.com
repository: https://github.com/horizech/fileheron_server

environment:
    sdk: ">=2.17.3 <3.0.0"

dependencies:
    # path: ^1.8.0
    args: ^2.3.1
    shelf: ^1.3.2
    http_server: ^1.0.0
dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.4
